# Generated by Django 5.0.1 on 2025-01-30 08:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название ресторана')),
            ],
            options={
                'verbose_name': 'Ресторан',
                'verbose_name_plural': 'Рестораны',
                'indexes': [models.Index(fields=['name'], name='restaurant__name_cf5999_idx')],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название секции')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='restaurant.restaurant', verbose_name='Ресторан')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный UUID')),
                ('number', models.IntegerField(verbose_name='Номер стола')),
                ('iiko_guid', models.CharField(blank=True, max_length=255, null=True, verbose_name='IIKO GUID')),
                ('qr', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR-код')),
                ('call_waiter', models.BooleanField(default=False, verbose_name='Вызов официанта')),
                ('call_time', models.DateTimeField(blank=True, null=True, verbose_name='Время вызова')),
                ('bill_waiter', models.BooleanField(default=False, verbose_name='Запрос счёта')),
                ('bill_time', models.DateTimeField(blank=True, null=True, verbose_name='Время запроса счёта')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurant.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'QR код',
                'verbose_name_plural': 'QR коды',
                'ordering': ['number'],
            },
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['restaurant', 'name'], name='restaurant__restaur_7d43bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('restaurant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('section', 'number')},
        ),
    ]
