# Generated by Django 5.0.1 on 2025-01-30 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['number'], 'verbose_name': 'Стол и его QR код', 'verbose_name_plural': 'Создания стола и его QR кода'},
        ),
    ]
