# Generated by Django 5.0.1 on 2025-01-30 09:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_table_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['number'], 'verbose_name': 'Стол и его QR код', 'verbose_name_plural': 'Создание столов и QR кодов'},
        ),
        migrations.AlterField(
            model_name='table',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Уникальный UUID'),
        ),
    ]
