# Generated by Django 5.0.1 on 2025-02-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_table_options_alter_table_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='iiko_department_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID подразделения в iiko'),
        ),
        migrations.AddField(
            model_name='table',
            name='iiko_waiter_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID официанта в iiko'),
        ),
        migrations.AddField(
            model_name='table',
            name='organization_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='GUID организации iiko'),
        ),
    ]
