# Generated by Django 5.0.1 on 2025-02-12 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_table_iiko_department_id_table_iiko_waiter_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='iiko_department_id',
        ),
        migrations.RemoveField(
            model_name='table',
            name='iiko_guid',
        ),
        migrations.RemoveField(
            model_name='table',
            name='iiko_waiter_id',
        ),
        migrations.RemoveField(
            model_name='table',
            name='organization_id',
        ),
    ]
